config/routes.rb
Rails.application.routes.draw do
  

  get 'api/patient'
  get 'api/disease'
  get 'api/addpatient'

  resources :diseasecodes

  devise_for :doctors, controllers: { registrations: "doctors/registrations", sessions: "doctors/sessions"}
=begin
devise_for :doctors, :controllers => { :sessions => "api1/v1/sessions" }
devise_scope :doctor do
  namespace :api1 do
    namespace :v1 do
      resources :sessions, :only => [:create, :destroy]
    end
  end
end
=end

resources :doctors

  resources :patients

  get 'welcome/index'

  devise_for :hospitaladmins
  devise_for :admins
  resources :dashboards, only: [:index]
  resources :hospitaladmin

   root 'welcome#index'

end

app/models/patient.rb
class Patient < ActiveRecord::Base
	belongs_to :hospitaladmin
end

app/controllers/patients_controller.rb
class PatientsController < ApplicationController
  before_action :authenticate_hospitaladmin!
  before_action :set_patient, only: [:show, :edit, :update, :destroy, :patientlist, :discharge]

  respond_to :html, :json

  def index
    @patients = @patients = current_hospitaladmin.patients.where(:discharge_status => 0)
    respond_with(@patients1)
  end

  def show
    @patient = Patient.find(params[:id])
    respond_with(@patient)
  end

  def new
    @patient = current_hospitaladmin.patients.new
    respond_with(@patient)
  end

  def edit
  end

  def create
    @patient = current_hospitaladmin.patients.new(patient_params)
    @patient.hospitaladmin_id = current_hospitaladmin.id
    @patient.discharge_status = 0
    @patient.save
    respond_with(@patient)
  end

  def update
    @patient.update(patient_params)
    respond_with(@patient)
  end

  def discharge
    
  end

  def destroy
    @patient.destroy
    respond_with(@patient)
  end

  #private
    def set_patient
      @patient = Patient.find(params[:id])
    end

    def patient_params
      params.require(:patient).permit(:first_name, :last_name, :email, :gender, :mi, :date_of_birth, :contact_no, :billing_id, :physician)
    end
end
#name=test&gender=male&date_of_birth=10/02/2010&contact_no=58475896&billing_id=25&physician=48

app/helpers/patients_helper.rb
module PatientsHelper
end

app/views/patients/_form.html.erb
<%= form_for(@patient) do |f| %>
  <% if @patient.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@patient.errors.count, "error") %> prohibited this patient from being saved:</h2>

      <ul>
      <% @patient.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  
                                    <div class="form-horizontal group-border stripped">
                                        
                                        <!-- End .form-group  -->
                                        <div class="form-group">
                                            <%= f.label :first_name, class:'col-sm-2 control-label' %>
                                            <div class="col-sm-10">
                                                <%= f.text_field :first_name, class:'form-control' %>
                                            </div>
                                        </div>
                                         <div class="form-group">
                                            <%= f.label :last_name, class:'col-sm-2 control-label' %>
                                            <div class="col-sm-10">
                                                <%= f.text_field :last_name, class:'form-control' %>
                                            </div>
                                        </div>
                                        <div class="form-group">
                                            <%= f.label :email, class:'col-sm-2 control-label' %>
                                            <div class="col-sm-10">
                                                <%= f.text_field :email, class:'form-control' %>
                                            </div>
                                        </div>
                                        <!-- End .form-group  -->
                                        <div class="form-group">
                                            <%= f.label :gender, class:'col-sm-2 control-label' %>
                                            <div class="col-sm-10">
                                               <%= f.text_field :gender, class:'form-control' %>
                                            </div>
                                        </div>
                                        <!-- End .form-group  -->
                                        <div class="form-group">
                                            <%= f.label :date_of_birth, class:'col-sm-2 control-label' %>
                                            <div class="col-sm-10">
                                               <%= f.text_field :date_of_birth, class:'form-control' %>
                                            </div>
                                        </div>
                                         <!-- End .form-group  -->
                                        <div class="form-group">
                                            <%= f.label :contact_no, class:'col-sm-2 control-label' %>
                                            <div class="col-sm-10">
                                               <%= f.text_field :contact_no, class:'form-control' %>
                                            </div>
                                        </div>
                                         <!-- End .form-group  -->
                                        <div class="form-group">
                                            <%= f.label :billing_id, class:'col-sm-2 control-label' %>
                                            <div class="col-sm-10">
                                               <%= f.text_field :billing_id, class:'form-control' %>
                                            </div>
                                        </div>
                                        <div class="form-group">
                                            <%= f.label :mi, class:'col-sm-2 control-label' %>
                                            <div class="col-sm-10">
                                               <%= f.text_field :mi, class:'form-control' %>
                                            </div>
                                        </div>
                                        <div class="form-group">
                                            <%= f.label :physician, class:'col-sm-2 control-label' %>
                                            <div class="col-sm-10">
                                            
                                            <%= select("patient", "physician", current_hospitaladmin.doctors.collect {|p| [ p.name, p.id] }, {include_blank: true}) %>
                                               
                                            </div>
                                        </div>
                                         <!-- End .form-group  -->
                                        <div class="form-group">
                                            <%= f.submit %>
                                        </div>
                                       
                                     
                                        
                                    </div>
                                

<% end %>

app/views/patients/edit.html.erb
<%= render 'layouts/head_content' %>
<h1>Editing Patient</h1>
<%= render 'form' %>

<%= link_to 'Show', @patient %> |
<%= link_to 'Back', patients_path %>
<%= render 'layouts/footer_content' %>

app/views/patients/index.html.erb
<%= render 'layouts/head_content' %>
<p id="notice"><%= notice %></p>
  <div class="panel panel-default plain toggle panelClose panelRefresh">
                                <!-- Start .panel -->
                                <div class="panel-heading white-bg">
                                    <h2 class="panel-title">Listing Patients</h2>
                                </div>
                                <div class="panel-body">
                                    <table class="table table-bordered">
                                        <thead>
                                            <tr>
                                                <th class="per3">
                                                    #
                                                </th>
                                                <th class="per15">First Name</th>
                                                <th class="per15">Last Name</th>
                                                <th class="per15">Email</th>
                                                <th class="per5">Gender</th>
                                                <th class="per20">MI</th>
                                                <th class="per10">Date-of-birth</th>
                                                <th class="per10">Contact No</th>
                                                <th class="per10">Billing ID</th>
                                                 <th class="per15">Attending Physician</th>
                                               <th colspan="3"></th>
                                            </tr>
                                        </thead>
                                        <tbody>
                                         <% 
                                         $count = 1
                                         @patients.each do |patient| %>
                                            <tr>
                                                <td>
                                                    <%= $count %>
                                                </td>
                                                       <td><%= patient.first_name %></td>
                                                       <td><%= patient.last_name %></td>
                                                       <td><%= patient.email %></td>
                                                        <td><%= patient.gender %></td>
                                                        <td><%= patient.mi %></td>
                                                        <td><%= patient.date_of_birth %></td>
                                                        <td><%= patient.contact_no %></td>
                                                        <td><%= patient.billing_id %></td>
                                                        <td><%= patient.physician %></td>
                                                <td><%= link_to patient, :data => {:no_turbolink => true } do %>
                                                  <i class="fa fa-eye fa-5"></i>
                                                 <% end %> 
                                                </td>
                                                <td>
                                                <%= link_to edit_patient_path(patient), :data => { :no_turbolink => true } do %>
                                                  <i class="fa fa-pencil-square fa-5"></i>
                                                <% end %>
                                                </td>
                                                <td><%= link_to patient, method: :delete, data: { confirm: 'Are you sure?', no_turbolink: true } do %>
                                                    <i class="fa fa-trash-o fa-5"></i>
                                                <% end %>
                                                </td>
                                                <td><%= link_to patient, method: :delete, data: { confirm: 'Are you sure?', no_turbolink: true } do %>
                                                    <i class="fa fa-trash-o fa-5"></i>
                                                <% end %>
                                                </td>
                                            </tr>
                                           <% 
                                           $count = $count+1 
                                           end %> 
                                        </tbody>
                                    </table>
                                    <%= link_to new_patient_path, :data => { :no_turbolink => true} do %>
                                     <button class="btn btn-success mr5 mb10" type="button">New Patient</button>
                                    <% end %>
                                </div>
                            </div>
           
<%= render 'layouts/footer_content' %>

app/views/patients/new.html.erb
<%= render 'layouts/head_content' %>
 <div class="panel panel-default plain toggle panelMove panelClose panelRefresh">
 <div class="panel-heading">
    <h2 class="panel-title">Add New Patient</h2>
 </div>
   <div class="panel-body pb0">
    <%= render 'form' %>
   </div>
 </div>
<%= link_to 'Back', patients_path, :data => {:no_turbolink => true } %>
<%= render 'layouts/footer_content' %>

app/views/patients/show.html.erb
<%= render 'layouts/head_content' %>
<p id="notice"><%= notice %></p>

<p>
  <strong>First Name:</strong>
  <%= @patient.first_name %>
</p>

<p>
  <strong>Last Name:</strong>
  <%= @patient.last_name %>
</p>

<p>
  <strong>Email:</strong>
  <%= @patient.email %>
</p>

<p>
  <strong>Gender:</strong>
  <%= @patient.gender %>
</p>

<p>
  <strong>MI:</strong>
  <%= @patient.mi %>
</p>

<p>
  <strong>Date-of-birth:</strong>
  <%= @patient.date_of_birth %>
</p>

<p>
  <strong>Contact-no:</strong>
  <%= @patient.contact_no %>
</p>

<p>
  <strong>Billing ID:</strong>
  <%= @patient.billing_id %>
</p>
<p>
  <strong>Physician:</strong>
  <%= @patient.physician %>
</p>

<%= link_to 'Edit', edit_patient_path(@patient) %> |
<%= link_to 'Back', patients_path %>
<%= render 'layouts/footer_content' %>