config/routes.rb
Rails.application.routes.draw do
  

  get 'api/patient'
  get 'api/disease'
  get 'api/addpatient'

  resources :diseasecodes

  devise_for :doctors, controllers: { registrations: "doctors/registrations", sessions: "doctors/sessions"}
=begin
devise_for :doctors, :controllers => { :sessions => "api1/v1/sessions" }
devise_scope :doctor do
  namespace :api1 do
    namespace :v1 do
      resources :sessions, :only => [:create, :destroy]
    end
  end
end
=end

resources :doctors

  resources :patients

  get 'welcome/index'

  devise_for :hospitaladmins
  devise_for :admins
  resources :dashboards, only: [:index]
  resources :hospitaladmin

   root 'welcome#index'

end

app/models/diseasecode.rb
class Diseasecode < ActiveRecord::Base
	belongs_to :hospitaladmin
end

app/controllers/diseasecodes_controller.rb
class DiseasecodesController < ApplicationController
  before_action :authenticate_hospitaladmin!
  before_action :set_diseasecode, only: [:show, :edit, :update, :destroy]

  respond_to :html, :json

  def index
    #@diseasecodes = Diseasecode.all
    @diseasecodes = current_hospitaladmin.diseasecodes.all
    respond_with(@diseasecodes)
  end

  def show
    respond_with(@diseasecode)
  end

  def new
    @diseasecode = Diseasecode.new
    respond_with(@diseasecode)
  end

  def edit
  end

  def create
    @diseasecode = Diseasecode.new(diseasecode_params)
    @diseasecode.hospitaladmin_id = current_hospitaladmin.id
    @diseasecode.save
    respond_with(@diseasecode)
  end

  def update
    @diseasecode.update(diseasecode_params)
    respond_with(@diseasecode)
  end

  def destroy
    @diseasecode.destroy
    respond_with(@diseasecode)
  end

  private
    def set_diseasecode
      @diseasecode = Diseasecode.find(params[:id])
    end

    def diseasecode_params
      params.require(:diseasecode).permit(:disease, :code, :description)
    end
end

app/helpers/diseasecodes_helper.rb
module DiseasecodesHelper
end

app/views/diseasecodes/_form.html.erb
<div class="panel panel-success plain toggle panelMove panelClose panelRefresh" id="jst_1">
                                <!-- Start .panel -->
                                <div class="panel-heading">
                                    <h4 class="panel-title">Horizontal form</h4>
                               </div>
                                <div class="panel-body">
                                    <p class="mb15">Add code and remark for the Disease</p>
                                    <% if @diseasecode.errors.any? %>
                                      <div class="alert alert-info">
                                        <h2><%= pluralize(@diseasecode.errors.count, "error") %> prohibited this diseasecode from being saved:</h2>
                                          <ul>
                                            <% @diseasecode.errors.full_messages.each do |message| %>
                                            <li><%= message %></li>
                                            <% end %>
                                          </ul>
                                      </div>
                                    <% end %>
                                    
                                   <%= form_for(@diseasecode, :html => {:class => "form-horizontal"}) do |f| %>
                                        <div class="form-group">
                                            <label class="col-sm-2 control-label" for="inputEmail3">Disease</label>
                                            <div class="col-sm-10">
                                            <%= f.text_field :disease, :class => 'form-control' %>
                                             
                                            </div>
                                        </div>
                                        <div class="form-group">
                                            <label class="col-sm-2 control-label" for="inputPassword3">Code</label>
                                            <div class="col-sm-10">
                                                <%= f.text_field :code, :class => 'form-control' %>
                                            </div>
                                        </div>
                                         <div class="form-group">
                                            <label class="col-sm-2 control-label" for="inputPassword3">Remark</label>
                                            <div class="col-sm-10">
                                                <%= f.text_area :description, :class => 'form-control' %>
                                            </div>
                                        </div>
                                     
                                        <div class="form-group">
                                            <div class="col-sm-offset-2 col-sm-10">
                                            <%= f.submit :class => 'btn btn-default' %>
                                            </div>
                                        </div>
                                   <% end %>
                                </div>
                            </div>

app/views/diseasecodes/edit.html.erb
<%= render 'layouts/head_content' %>
<h1>Editing Disease Code</h1>

<%= render 'form' %>

<%= link_to 'Show', @diseasecode , data: { no_turbolink: true } %> |
<%= link_to 'Back', diseasecodes_path , data: { no_turbolink: true } %>
<%= render 'layouts/footer_content' %>

app/views/diseasecodes/index.html.erb
<%= render 'layouts/head_content' %>
<p id="notice"><%= notice %></p>
  <div class="panel panel-default plain toggle panelClose panelRefresh">
                                <!-- Start .panel -->
                                <div class="panel-heading white-bg">
                                    <h2 class="panel-title">Listing Disease</h2>
                                </div>
                                <div class="panel-body">
                                    <table class="table table-bordered">
                                        <thead>
                                            <tr>
                                                <th class="per5">
                                                    #
                                                </th>
                                                <th class="per25">Disease</th>
                                                <th class="per20">Code</th>
                                                <th class="per40">Remark</th>
                                               <th colspan="10"></th>
                                            </tr>
                                        </thead>
                                        <tbody>
                                         <% 
                                         $count = 1
                                         @diseasecodes.each do |diseasecode| %>
                                            <tr>
                                                <td>
                                                    <%= $count %>
                                                </td>
                                                       <td><%= diseasecode.disease %></td>
                                                        <td><%= diseasecode.code %></td>
                                                        <td><%= diseasecode.description %></td>
                                                
                                                <td>
                                                <%= link_to edit_diseasecode_path(diseasecode), :data => { :no_turbolink => true } do %>
                                                  <i class="fa fa-pencil-square fa-5"></i>
                                                <% end %>
                                                </td>
                                                <td><%= link_to diseasecode, method: :delete, data: { confirm: 'Are you sure?', no_turbolink: true } do %>
                                                    <i class="fa fa-trash-o fa-5"></i>
                                                <% end %>
                                                </td>
                                            </tr>
                                           <% 
                                           $count = $count+1 
                                           end %> 
                                        </tbody>
                                    </table>
                                    <%= link_to new_diseasecode_path, :data => { :no_turbolink => true} do %>
                                     <button class="btn btn-success mr5 mb10" type="button">New Patient</button>
                                    <% end %>
                                </div>
                            </div>
           
<%= render 'layouts/footer_content' %>

app/views/diseasecodes/new.html.erb
<%= render 'layouts/head_content' %>
<h1>New Disease Code</h1>

<%= render 'form' %>

<%= link_to 'Back', diseasecodes_path, data: { no_turbolink: true } %>
<%= render 'layouts/footer_content' %>

app/views/diseasecodes/show.html.erb
<%= render 'layouts/head_content' %>
<p id="notice"><%= notice %></p>

<p>
  <strong>Disease:</strong>
  <%= @diseasecode.disease %>
</p>

<p>
  <strong>Code:</strong>
  <%= @diseasecode.code %>
</p>

<p>
  <strong>Hospitaladmin:</strong>
  <%= @diseasecode.hospitaladmin_id %>
</p>

<p>
  <strong>Description:</strong>
  <%= @diseasecode.description %>
</p>

<%= link_to 'Edit', edit_diseasecode_path(@diseasecode) %> |
<%= link_to 'Back', diseasecodes_path %>
<%= render 'layouts/footer_content' %>