config/routes.rb
Rails.application.routes.draw do
  

  get 'api/patient'
  get 'api/disease'
  get 'api/addpatient'

  resources :diseasecodes

  devise_for :doctors, controllers: { registrations: "doctors/registrations", sessions: "doctors/sessions"}
=begin
devise_for :doctors, :controllers => { :sessions => "api1/v1/sessions" }
devise_scope :doctor do
  namespace :api1 do
    namespace :v1 do
      resources :sessions, :only => [:create, :destroy]
    end
  end
end
=end

resources :doctors

  resources :patients

  get 'welcome/index'

  devise_for :hospitaladmins
  devise_for :admins
  resources :dashboards, only: [:index]
  resources :hospitaladmin

   root 'welcome#index'

end

app/models/admin.rb
class Admin < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/models/diseasecode.rb
class Diseasecode < ActiveRecord::Base
	belongs_to :hospitaladmin
end

app/models/doctor.rb
class Doctor < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  belongs_to :hospitaladmin
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

end

app/models/hospitaladmin.rb
class Hospitaladmin < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
  has_many :doctors
  has_many :patients
  has_many :diseasecodes       
end

app/models/patient.rb
class Patient < ActiveRecord::Base
	belongs_to :hospitaladmin
end

app/controllers/api_controller.rb
class ApiController < ApplicationController
  respond_to :json
  def patient
    @d_id = params[:d_id]
    @patients = Patient.where(:discharge_status => 0, :physician => @d_id)
     respond_with(@patients)
  end
    def disease
   @diseasecode = Diseasecode.all
     respond_with(@diseasecode)
  end
  def addpatient
  	  @patient = Patient.create(params[:id])
  	  @patient.first_name = params[:first_name]
      @patient.last_name = params[:last_name]
      @patient.email = params[:email]
  	  @patient.hospitaladmin_id = params[:hospitaladmin_id]
  	  @patient.mi = params[:mi]
  	  @patient.contact_no = params[:contact_no]
  	  @patient.physician = params[:physician]
  	  @patient.discharge_status = 0
  flash[:notice] = 'Patient was successfully created.' if @patient.save
  respond_with(@patient)
  end

      def patient_params
      params.require(:patient).permit(:d_id, :first_name, :last_name, :email, :hospitaladmin_id, :mi, :contact_no, :physician)
    end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/dashboards_controller.rb
class DashboardsController < ApplicationController
	def index
		@hospitals = Hospitaladmin.all
	end
end

app/controllers/diseasecodes_controller.rb
class DiseasecodesController < ApplicationController
  before_action :authenticate_hospitaladmin!
  before_action :set_diseasecode, only: [:show, :edit, :update, :destroy]

  respond_to :html, :json

  def index
    #@diseasecodes = Diseasecode.all
    @diseasecodes = current_hospitaladmin.diseasecodes.all
    respond_with(@diseasecodes)
  end

  def show
    respond_with(@diseasecode)
  end

  def new
    @diseasecode = Diseasecode.new
    respond_with(@diseasecode)
  end

  def edit
  end

  def create
    @diseasecode = Diseasecode.new(diseasecode_params)
    @diseasecode.hospitaladmin_id = current_hospitaladmin.id
    @diseasecode.save
    respond_with(@diseasecode)
  end

  def update
    @diseasecode.update(diseasecode_params)
    respond_with(@diseasecode)
  end

  def destroy
    @diseasecode.destroy
    respond_with(@diseasecode)
  end

  private
    def set_diseasecode
      @diseasecode = Diseasecode.find(params[:id])
    end

    def diseasecode_params
      params.require(:diseasecode).permit(:disease, :code, :description)
    end
end

app/controllers/doctors/sessions_controller.rb
class Doctors::SessionsController < Devise::SessionsController
respond_to :html, :json
def create
    resource = warden.authenticate!(:scope => resource_name, :recall => "#{controller_path}#new")
    set_flash_message(:notice, :signed_in) if is_navigational_format?
    sign_in(resource_name, resource)
    respond_to do |format|  
      format.html { respond_with resource, :location => after_sign_in_path_for(resource) }  
      format.json {  
         return render :json => {  :success => true, 
          
         } 
      }  
    end
  end
  def destroy  
    super  
  end  
# before_filter :configure_sign_in_params, only: [:create]

  # GET /resource/sign_in
  # def new
  #   super
  # end

  # POST /resource/sign_in
  # def create
  #   super
  # end

  # DELETE /resource/sign_out
  # def destroy
  #   super
  # end

  # protected

  # You can put the params you want to permit in the empty array.
  # def configure_sign_in_params
  #   devise_parameter_sanitizer.for(:sign_in) << :attribute
  # end
end

app/controllers/doctors/unlocks_controller.rb
class Doctors::UnlocksController < Devise::UnlocksController
  # GET /resource/unlock/new
  # def new
  #   super
  # end

  # POST /resource/unlock
  # def create
  #   super
  # end

  # GET /resource/unlock?unlock_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after sending unlock password instructions
  # def after_sending_unlock_instructions_path_for(resource)
  #   super(resource)
  # end

  # The path used after unlocking the resource
  # def after_unlock_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/hospitaladmin_controller.rb
class HospitaladminController < ApplicationController
  def index
  	@doctors = current_hospitaladmin.doctors.all
  	@patients = current_hospitaladmin.patients.all
  end
end

app/controllers/patientlist_controller.rb
class ApiController < ApplicationController
  respond_to :json
  def patient
   @patients = Patient.all
     respond_with(@patients)
  end
    def disease
   @diseasecode = Diseasecode.all
     respond_with(@diseasecode)
  end
end

app/controllers/patients_controller.rb
class PatientsController < ApplicationController
  before_action :authenticate_hospitaladmin!
  before_action :set_patient, only: [:show, :edit, :update, :destroy, :patientlist, :discharge]

  respond_to :html, :json

  def index
    @patients = @patients = current_hospitaladmin.patients.where(:discharge_status => 0)
    respond_with(@patients1)
  end

  def show
    @patient = Patient.find(params[:id])
    respond_with(@patient)
  end

  def new
    @patient = current_hospitaladmin.patients.new
    respond_with(@patient)
  end

  def edit
  end

  def create
    @patient = current_hospitaladmin.patients.new(patient_params)
    @patient.hospitaladmin_id = current_hospitaladmin.id
    @patient.discharge_status = 0
    @patient.save
    respond_with(@patient)
  end

  def update
    @patient.update(patient_params)
    respond_with(@patient)
  end

  def discharge
    
  end

  def destroy
    @patient.destroy
    respond_with(@patient)
  end

  #private
    def set_patient
      @patient = Patient.find(params[:id])
    end

    def patient_params
      params.require(:patient).permit(:first_name, :last_name, :email, :gender, :mi, :date_of_birth, :contact_no, :billing_id, :physician)
    end
end
#name=test&gender=male&date_of_birth=10/02/2010&contact_no=58475896&billing_id=25&physician=48

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
 
  def index

  	if admin_signed_in? 
  		redirect_to url_for(:controller => :dashboards, :action => :index)
   	else
   		if hospitaladmin_signed_in? 
  			redirect_to url_for(:controller => :hospitaladmin, :action => :index)
   		else
   			redirect_to new_hospitaladmin_session_path
   		end
   	end

   		

  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/dashboards_helper.rb
module DashboardsHelper
end

app/helpers/diseasecodes_helper.rb
module DiseasecodesHelper
end

app/helpers/hospitaladmin_helper.rb
module HospitaladminHelper
end

app/helpers/patientlist_helper.rb
module PatientlistHelper
end

app/helpers/patients_helper.rb
module PatientsHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/dashboards/index.html.erb
<%= render 'layouts/adminheader' %>
<!-- col-lg-12 start here -->
                            <div class="panel panel-default plain toggle panelClose panelRefresh" id="jst_3">
                                <!-- Start .panel -->
                                <div class="panel-heading white-bg">
                                    <h4 class="panel-title">List of all Hospitals</h4>
                                <div class="panel-controls"><a class="panel-refresh" href="#"><i class="im-spinner12"></i></a><a class="toggle panel-minimize" href="#"><i class="im-minus"></i></a><a class="panel-close" href="#"><i class="im-close"></i></a></div></div>
                                <div class="panel-body">
                                    <div class="slimScrollDiv" style="position: relative; overflow: hidden; width: 100%; height: auto;"><div class="table-responsive" style="overflow: hidden; width: 100%; height: auto;"><table class="table table-bordered">
                                        <thead>
                                            <tr>
                                                <th class="per5">
                                                    #
                                                </th>
                                                <th class="per40">Email</th>
                                                <th class="per40">Created at</th>
                                                <th class="per15">Action</th>
                                            </tr>
                                        </thead>
                                        <tbody>
                                        <% $i = 1 %>
                                        <% @hospitals.each do |hospital| %>
                                            <tr>
                                                <td>
                                                    <%= $i %>
                                                </td>
                                                <td><%= hospital.email %></td>
                                                <td><%= hospital.created_at %></td>
                                                <td>---</td>
                                            </tr>
                                            <% $i = $i+1 %>
                                         <% end %>    
                                           
                                        </tbody>
                                    </table>
                                 
                                     <%= link_to "Add Hospital", new_hospitaladmin_registration_path, :method => :get, :class => 'btn btn-success mr5 mb10' %>   
                                    </div><div class="slimScrollBar ui-draggable" style="background: none repeat scroll 0% 0% rgb(255, 255, 255); height: 5px; position: absolute; bottom: 3px; opacity: 0.4; display: none; border-radius: 5px 5px 5px 5px; z-index: 99; width: 953px; left: 0px;"></div><div class="slimScrollRail" style="width: 100%; height: 5px; position: absolute; bottom: 3px; display: none; border-radius: 5px 5px 5px 5px; background: none repeat scroll 0% 0% rgb(51, 51, 51); opacity: 1; z-index: 90;"></div></div>
                                </div>
                            </div>
       <%= render 'layouts/footer_content' %>                

app/views/welcome/index.html.erb
<h1>Welcome#index</h1>
<% if admin_signed_in? %>
<% redirect_to dashboards %>
<h3>you have succesfully signed in</h3>
<%= link_to "Sign Out", destroy_admin_session_path, :method => :delete %>

<% else %>

<h1> welcom to rails community</h1>
<%= link_to "Sign In", new_admin_session_path, :method => :get %>

<% end %>