config/routes.rb
Rails.application.routes.draw do
  

  get 'api/patient'
  get 'api/disease'
  get 'api/addpatient'

  resources :diseasecodes

  devise_for :doctors, controllers: { registrations: "doctors/registrations", sessions: "doctors/sessions"}
=begin
devise_for :doctors, :controllers => { :sessions => "api1/v1/sessions" }
devise_scope :doctor do
  namespace :api1 do
    namespace :v1 do
      resources :sessions, :only => [:create, :destroy]
    end
  end
end
=end

resources :doctors

  resources :patients

  get 'welcome/index'

  devise_for :hospitaladmins
  devise_for :admins
  resources :dashboards, only: [:index]
  resources :hospitaladmin

   root 'welcome#index'

end

app/models/admin.rb
class Admin < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/models/diseasecode.rb
class Diseasecode < ActiveRecord::Base
	belongs_to :hospitaladmin
end

app/models/doctor.rb
class Doctor < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  belongs_to :hospitaladmin
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

end

app/models/hospitaladmin.rb
class Hospitaladmin < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
  has_many :doctors
  has_many :patients
  has_many :diseasecodes       
end

app/models/patient.rb
class Patient < ActiveRecord::Base
	belongs_to :hospitaladmin
end

app/controllers/api_controller.rb
class ApiController < ApplicationController
  respond_to :json
  def patient
    @d_id = params[:d_id]
    @patients = Patient.where(:discharge_status => 0, :physician => @d_id)
     respond_with(@patients)
  end
    def disease
   @diseasecode = Diseasecode.all
     respond_with(@diseasecode)
  end
  def addpatient
  	  @patient = Patient.create(params[:id])
  	  @patient.first_name = params[:first_name]
      @patient.last_name = params[:last_name]
      @patient.email = params[:email]
  	  @patient.hospitaladmin_id = params[:hospitaladmin_id]
  	  @patient.mi = params[:mi]
  	  @patient.contact_no = params[:contact_no]
  	  @patient.physician = params[:physician]
  	  @patient.discharge_status = 0
  flash[:notice] = 'Patient was successfully created.' if @patient.save
  respond_with(@patient)
  end

      def patient_params
      params.require(:patient).permit(:d_id, :first_name, :last_name, :email, :hospitaladmin_id, :mi, :contact_no, :physician)
    end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/dashboards_controller.rb
class DashboardsController < ApplicationController
	def index
		@hospitals = Hospitaladmin.all
	end
end

app/controllers/diseasecodes_controller.rb
class DiseasecodesController < ApplicationController
  before_action :authenticate_hospitaladmin!
  before_action :set_diseasecode, only: [:show, :edit, :update, :destroy]

  respond_to :html, :json

  def index
    #@diseasecodes = Diseasecode.all
    @diseasecodes = current_hospitaladmin.diseasecodes.all
    respond_with(@diseasecodes)
  end

  def show
    respond_with(@diseasecode)
  end

  def new
    @diseasecode = Diseasecode.new
    respond_with(@diseasecode)
  end

  def edit
  end

  def create
    @diseasecode = Diseasecode.new(diseasecode_params)
    @diseasecode.hospitaladmin_id = current_hospitaladmin.id
    @diseasecode.save
    respond_with(@diseasecode)
  end

  def update
    @diseasecode.update(diseasecode_params)
    respond_with(@diseasecode)
  end

  def destroy
    @diseasecode.destroy
    respond_with(@diseasecode)
  end

  private
    def set_diseasecode
      @diseasecode = Diseasecode.find(params[:id])
    end

    def diseasecode_params
      params.require(:diseasecode).permit(:disease, :code, :description)
    end
end

app/controllers/hospitaladmin_controller.rb
class HospitaladminController < ApplicationController
  def index
  	@doctors = current_hospitaladmin.doctors.all
  	@patients = current_hospitaladmin.patients.all
  end
end

app/controllers/patientlist_controller.rb
class ApiController < ApplicationController
  respond_to :json
  def patient
   @patients = Patient.all
     respond_with(@patients)
  end
    def disease
   @diseasecode = Diseasecode.all
     respond_with(@diseasecode)
  end
end

app/controllers/patients_controller.rb
class PatientsController < ApplicationController
  before_action :authenticate_hospitaladmin!
  before_action :set_patient, only: [:show, :edit, :update, :destroy, :patientlist, :discharge]

  respond_to :html, :json

  def index
    @patients = @patients = current_hospitaladmin.patients.where(:discharge_status => 0)
    respond_with(@patients1)
  end

  def show
    @patient = Patient.find(params[:id])
    respond_with(@patient)
  end

  def new
    @patient = current_hospitaladmin.patients.new
    respond_with(@patient)
  end

  def edit
  end

  def create
    @patient = current_hospitaladmin.patients.new(patient_params)
    @patient.hospitaladmin_id = current_hospitaladmin.id
    @patient.discharge_status = 0
    @patient.save
    respond_with(@patient)
  end

  def update
    @patient.update(patient_params)
    respond_with(@patient)
  end

  def discharge
    
  end

  def destroy
    @patient.destroy
    respond_with(@patient)
  end

  #private
    def set_patient
      @patient = Patient.find(params[:id])
    end

    def patient_params
      params.require(:patient).permit(:first_name, :last_name, :email, :gender, :mi, :date_of_birth, :contact_no, :billing_id, :physician)
    end
end
#name=test&gender=male&date_of_birth=10/02/2010&contact_no=58475896&billing_id=25&physician=48

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
 
  def index

  	if admin_signed_in? 
  		redirect_to url_for(:controller => :dashboards, :action => :index)
   	else
   		if hospitaladmin_signed_in? 
  			redirect_to url_for(:controller => :hospitaladmin, :action => :index)
   		else
   			redirect_to new_hospitaladmin_session_path
   		end
   	end

   		

  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/dashboards_helper.rb
module DashboardsHelper
end

app/helpers/diseasecodes_helper.rb
module DiseasecodesHelper
end

app/helpers/hospitaladmin_helper.rb
module HospitaladminHelper
end

app/helpers/patientlist_helper.rb
module PatientlistHelper
end

app/helpers/patients_helper.rb
module PatientsHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/layouts/_adminheader.html.erb
<body class="ovh">
        <div id="preloader">
            <div id="preloader-logo">
                <img src="/assets/preloader-logo.png" alt="Logo">
            </div>
            <div id="preloader-icon">
                <i class="im-spinner icon-spin"></i>
            </div>
        </div>
        <!-- Start #header -->
        <div id="header">
            <div class="container-fluid">
                <div class="navbar">
                    <div class="navbar-header">
                        <!-- Show navigation toggle on phones -->
                        <button id="showNav" class="navbar-toggle" type="button">
                            <span class="sr-only">Toggle navigation</span>
                            <span class="icon-bar"></span>
                            <span class="icon-bar"></span>
                            <span class="icon-bar"></span>
                        </button>
                        <!-- Show logo for large screens and laptops -->
                        <span class="navbar-brand visible-lg visible-md">
                            <img src="/assets/logo.png" alt="Jump start">
                        </span>
                        <!-- Show logo for small screens -->
                        <span class="navbar-brand hidden-lg hidden-md hidden-xs">
                            <img src="/assets/logo-sm.png" alt="Jump start">
                        </span>
                    </div>
                    <% if admin_signed_in? || doctor_signed_in? || hospitaladmin_signed_in? %>
  

                    <nav id="top-nav" class="navbar-no-collapse" role="navigation">
                        <!-- navbar search form -->
                       
                        <!-- Navbar nav -->
                        <ul class="nav navbar-nav pull-right">
                            
                           
                            <li class="dropdown">
                                <a href="#" data-toggle="dropdown">
                                    <img class="avatar" src="/assets/avatars/1.jpg" width="36" height="36" alt="Jonh Doe"> <span class="avatar-name"><%= current_admin.email %></span>
                                    <span class="caret ml5"></span>
                                </a>
                                <ul class="dropdown-menu right" role="menu">
                                    <li><a href="#"><i class="im-user"></i> Profile</a>
                                    </li>
                                    <li><a href="#"><i class="im-cog2"></i> Settings</a>
                                    </li>
                                    <li><a href="#"><i class="im-question3"></i> Help</a>
                                    </li>
                                    <li>
                                    <%= link_to "Logout", destroy_admin_session_path, :method => :delete %>
                                    </li>
                                </ul>
                            </li>
                           
                        </ul>
                    </nav>
                    <% end %>
                </div>
            </div>
        </div>
        <!-- End #header -->
        <!-- Start #sidebar -->
        <aside id="sidebar">
            <!-- Start .sidebar-inner -->
            <div class="sidebar-inner">
                <!-- Start .toggle-sidebar -->
                <div class="toggle-sidebar">
                    <a href="#"><i class="im-arrow7"></i></a>
                </div>
                <!-- End .toggle-sidebar -->
                <!-- Start .option-buttons -->
                <div class="option-buttons">
                    <div class="option-buttons-inner">
                      <h5 class="sidebar-title">Navigation</h5>
                    </div>
                </div>
                <!-- End .option-buttons -->
                <!-- Start .sidebar-scrollarea -->
                <div class="sidebar-scrollarea">
                    <ul id="sideNav" class="nav nav-pills nav-stacked">
                        <li> <%= link_to dashboards_path, :data =>{ :no_turbolink => true } do %>
                            <i class="im-screen"></i><span class="txt">Dashboard</span>
                         <% end %>   
                        </li>
                        <li> <%= link_to new_hospitaladmin_registration_path, :data =>{ :no_turbolink => true } do %>
                            <i class="fa fa-medkit"></i><span class="txt">Add Hospital</span>
                         <% end %>   
                        </li>
                        
                     
                    </ul>
                    <div class="clearfix"></div>
                </div>
                <!-- End .sidebar-scrollarea -->
            </div>
            <!-- End .sidebar-inner -->
        </aside>
        <!-- End #sidebar -->
      
        <!-- End .sidebar-inner -->
        </aside>
        <!-- Start #right-sidebar -->
        <!-- Start #content -->
        <div id="content">
            <!-- Start .content-wrapper -->
            <div class="content-wrapper">
                <div id="page-heading" class="page-header">
                    <h2><i class="icon im-home2"></i> Dashboard</h2>
                    <!-- Start .bredcrumb -->
                    <ul id="crumb" class="breadcrumb">
                    </ul>
                    <!-- End .breadcrumb -->
                </div>
                <!-- Start .content-inner -->
                <div class="content-inner">
                    <div class="row">
                        <!-- Start .row -->
                        <div class="col-lg-12">

app/views/layouts/_footer.html.erb
<!-- End #content -->
        <!-- Javascripts -->
        <!-- Important javascript libs(put in all pages) -->
        <script src="http://code.jquery.com/jquery-2.1.1.min.js"></script>
        <script>
        window.jQuery || document.write('<script src="/assets/libs/jquery-2.1.1.min.js">\x3C/script>')
        </script>
        <script src="http://code.jquery.com/ui/1.10.4/jquery-ui.js"></script>
        <script>
        window.jQuery || document.write('<script src="/assets/libs/jquery-ui-1.10.4.min.js">\x3C/script>')
        </script>
        <!--[if lt IE 9]>
  <script type="text/javascript" src="assets/js/libs/excanvas.min.js"></script>
  <script type="text/javascript" src="http://html5shim.googlecode.com/svn/trunk/html5.js"></script>
  <script type="text/javascript" src="assets/js/libs/respond.min.js"></script>
<![endif]-->
        <!-- Bootstrap plugins -->
        <script src="/assets/bootstrap/bootstrap.js"></script>
        <!-- Core plugins ( not remove ) -->
        <script src="/assets/libs/modernizr.custom.js"></script>
        <!-- Handle responsive view functions -->
        <script src="/assets/jRespond.min.js"></script>
        <!-- Custom scroll for sidebars,tables and etc. -->
        <script src="/assets/core/slimscroll/jquery.slimscroll.min.js"></script>
        <script src="/assets/core/slimscroll/jquery.slimscroll.horizontal.min.js"></script>
        <!-- Highlight code blocks -->
        <script src="/assets/misc/highlight/highlight.pack.js"></script>
        <!-- Handle template sounds -->
        <script src="/assets/misc/ion-sound/ion.sound.js"></script>
        <!-- Proivde quick search for many widgets -->
        <script src="/assets/core/quicksearch/jquery.quicksearch.js"></script>
        <!-- Prompt modal -->
        <script src="/assets/ui/bootbox/bootbox.js"></script>
        <!-- Other plugins ( load only nessesary plugins for every page) -->
        <script src="/assets/forms/icheck/jquery.icheck.js"></script>
        <script src="/assets/charts/flot/jquery.flot.custom.js"></script>
        <script src="/assets/charts/flot/jquery.flot.pie.js"></script>
        <script src="/assets/charts/flot/jquery.flot.resize.js"></script>
        <script src="/assets/charts/flot/jquery.flot.time.js"></script>
        <script src="/assets/charts/flot/jquery.flot.growraf.js"></script>
        <script src="/assets/charts/flot/jquery.flot.categories.js"></script>
        <script src="/assets/charts/flot/jquery.flot.stack.js"></script>
        <script src="/assets/charts/flot/jquery.flot.orderBars.js"></script>
        <script src="/assets/charts/flot/jquery.flot.tooltip.min.js"></script>
        <script src="/assets/charts/flot/date.js"></script>
        <script src="/assets/charts/sparklines/jquery.sparkline.js"></script>
        <script src="/assets/charts/pie-chart/jquery.easy-pie-chart.js"></script>
        <script src="/assets/ui/weather/skyicons.js"></script>
        <script src="/assets/ui/calendar/fullcalendar.js"></script>
        <script src="/assets/jquery.appStart.js"></script>
        <script src="/assets/app.js"></script>
        <script src="/assets/pages/dashboard.js"></script>
</body>
</html>

app/views/layouts/_footer_content.erb
</div>
                      
                    </div>
                    <!-- End .row -->
                </div>
                <!-- End .content-inner -->
            </div>
            <!-- End .content-wrapper -->
            <div class="clearfix"></div>
        </div>

app/views/layouts/_head_content.erb
<body class="ovh">
        <div id="preloader">
            <div id="preloader-logo">
                <img src="/assets/preloader-logo.png" alt="Logo">
            </div>
            <div id="preloader-icon">
                <i class="im-spinner icon-spin"></i>
            </div>
        </div>
        <!-- Start #header -->
        <div id="header">
            <div class="container-fluid">
                <div class="navbar">
                    <div class="navbar-header">
                        <!-- Show navigation toggle on phones -->
                        <button id="showNav" class="navbar-toggle" type="button">
                            <span class="sr-only">Toggle navigation</span>
                            <span class="icon-bar"></span>
                            <span class="icon-bar"></span>
                            <span class="icon-bar"></span>
                        </button>
                        <!-- Show logo for large screens and laptops -->
                        <span class="navbar-brand visible-lg visible-md" href="index.html">
                            <img src="/assets/logo.png" alt="Jump start">
                        </span>
                        <!-- Show logo for small screens -->
                        <span class="navbar-brand hidden-lg hidden-md hidden-xs" href="index.html">
                            <img src="/assets/logo-sm.png" alt="Jump start">
                        </span>
                    </div>
                    <nav id="top-nav" class="navbar-no-collapse" role="navigation">
                       
                        <!-- Navbar nav -->
                        <ul class="nav navbar-nav pull-right">
                           
                         
                         
                            <li class="dropdown">
                                <a href="#" data-toggle="dropdown">
                                    <img class="avatar" src="/assets/avatars/1.jpg" width="36" height="36" alt="Jonh Doe"> <span class="avatar-name">
                                    <% if hospitaladmin_signed_in? %>
                                    <%= current_hospitaladmin.email %>
                                    <% end %>
                                    </span>
                                    <span class="caret ml5"></span>
                                </a>
                                <ul class="dropdown-menu right" role="menu">
                                    <li><a href="profile.html"><i class="im-user"></i> Profile</a>
                                    </li>
                                    <li><a href="#"><i class="im-cog2"></i> Settings</a>
                                    </li>
                                    <li><a href="#"><i class="im-question3"></i> Help</a>
                                    </li>
                                    <li>
                                    <%= link_to "Logout", destroy_hospitaladmin_session_path, :method => :delete %>
                                    </li>
                                </ul>
                            </li>
                        </ul>
                    </nav>
                </div>
            </div>
        </div>
        <!-- End #header -->
        <!-- Start #sidebar -->
        <aside id="sidebar">
            <!-- Start .sidebar-inner -->
            <div class="sidebar-inner">
                <!-- Start .toggle-sidebar -->
                <div class="toggle-sidebar">
                    <a href="#"><i class="im-arrow7"></i></a>
                </div>
                <!-- End .toggle-sidebar -->
                <!-- Start .option-buttons -->
                <div class="option-buttons">
                    <div class="option-buttons-inner">
                 <h5 class="sidebar-title">Navigation</h5>
                    </div>
                </div>
                <!-- End .option-buttons -->
                <!-- Start .sidebar-scrollarea -->
                <div class="sidebar-scrollarea">
                    
                    <ul id="sideNav" class="nav nav-pills nav-stacked">
                       <li>
                       <%= link_to hospitaladmin_index_path, :data => { :no_turbolink => true } do %>   
                           <i class="im-screen"></i><span class="txt">Dashboard</span>
                       <% end %>
                        </li>
                        <li class="hasSub">
                            <a href="#" class="notExpand"><i class="im-arrow-down2 sideNav-arrow rotate0"></i><i class="fa fa-wheelchair"></i> <span class="txt">Doctor</span></a>
                            <ul class="sub" style="display: none;">
                                <li>
                                    <a href="#">
                                    <i class="im-arrow-right3"></i><span class="txt">All Doctor</span>
                                    </a>    
                                </li>
                                <li>
                                    <%= link_to new_doctor_registration_path, data: { no_turbolink: true } do %>
                                    <i class="im-arrow-right3"></i><span class="txt">Add Doctor</span>
                                    <% end %>    
                                </li>
                            </ul>
                        </li>
                        <li class="hasSub">
                            <a href="#" class="notExpand"><i class="im-arrow-down2 sideNav-arrow rotate0"></i><i class="fa fa-wheelchair"></i> <span class="txt">Disease</span></a>
                            <ul class="sub" style="display: none;">
                                <li>
                                    <%= link_to diseasecodes_path, data: { no_turbolink: true } do %>
                                    <i class="im-arrow-right3"></i><span class="txt">All Disease</span>
                                    <% end %>    
                                </li>
                                <li>
                                    <%= link_to new_diseasecode_path, data: { no_turbolink: true } do %>
                                    <i class="im-arrow-right3"></i><span class="txt">Add Disease</span>
                                    <% end %>    
                                </li>
                            </ul>
                        </li>
                        <li class="hasSub">
                            <a href="#" class="notExpand"><i class="im-arrow-down2 sideNav-arrow rotate0"></i><i class="fa fa-wheelchair"></i> <span class="txt">Patient</span></a>
                            <ul class="sub" style="display: none;">
                                <li>
                                    <%= link_to patients_path, data: { no_turbolink: true } do %>
                                    <i class="im-arrow-right3"></i><span class="txt">All Patient</span>
                                    <% end %>    
                                </li>
                                <li>
                                    <%= link_to new_patient_path, data: { no_turbolink: true } do %>
                                    <i class="im-arrow-right3"></i><span class="txt">Add Patient</span>
                                    <% end %>    
                                </li>
                            </ul>
                        </li>
                        
                       
                    </ul>
                    <div class="clearfix"></div>
                </div>
                <!-- End .sidebar-scrollarea -->
            </div>
            <!-- End .sidebar-inner -->
        </aside>
        <!-- End #sidebar -->
      
        </aside>
        <!-- Start #right-sidebar -->
        <!-- Start #content -->
        <div id="content">
            <!-- Start .content-wrapper -->
            <div class="content-wrapper">
                <div id="page-heading" class="page-header">
                    <h2><i class="icon im-home2"></i> Dashboard</h2>
                    <!-- Start .bredcrumb -->
                    <ul id="crumb" class="breadcrumb">
                    </ul>
                    <!-- End .breadcrumb -->
                </div>
                <!-- Start .content-inner -->
                <div class="content-inner">
                    <!-- Start .row -->
                    <div class="row">
                        <div class="col-lg-12">
                            <div class="row">

app/views/layouts/_header.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Hospitalapp</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <link href='http://fonts.googleapis.com/css?family=Roboto:400,300,300italic,400italic,700' rel='stylesheet' type='text/css'>
  <link href="//maxcdn.bootstrapcdn.com/font-awesome/4.2.0/css/font-awesome.min.css" rel="stylesheet">
        <!-- Css files -->
        <!-- Icons -->
        <link href="/assets/icons.css" rel="stylesheet" />
        <!-- Bootstrap stylesheets (included template modifications) -->
        <link href="/assets/bootstrap.css" rel="stylesheet" />
        <!-- jQueryUI -->
        <link href="/assets/appstart-theme/jquery.ui.all.css" rel="stylesheet" />
        <!-- Plugins stylesheets (all plugin custom css) -->
        <link href="/assets/plugins.css" rel="stylesheet" />
        <!-- Main stylesheets (template main css file) -->
        <link href="/assets/main.css" rel="stylesheet" />
        <!-- Custom stylesheets ( Put your own changes here ) -->
        <link href="/assets/custom.css" rel="stylesheet" />
        <!-- Fav and touch icons -->
        <link rel="apple-touch-icon-precomposed" sizes="144x144" href="/assets/ico/apple-touch-icon-144-precomposed.png">
        <link rel="apple-touch-icon-precomposed" sizes="114x114" href="/assets/ico/apple-touch-icon-114-precomposed.png">
        <link rel="apple-touch-icon-precomposed" sizes="72x72" href="/assets/ico/apple-touch-icon-72-precomposed.png">
        <link rel="apple-touch-icon-precomposed" href="assets/ico/apple-touch-icon-57-precomposed.png">
        <link rel="icon" href="/assets/ico/favicon.ico" type="image/png">
  <%= csrf_meta_tags %>
</head>

app/views/layouts/application.html.erb
<%= render 'layouts/header' %>
<%= yield %>
<%= render 'layouts/footer' %>
 

app/views/user_notifier/send_doctor_email.erb
	<!DOCTYPE html>
<html>
  <head>
    <meta content='text/html; charset=UTF-8' http-equiv='Content-Type' />
  </head>
  <body>
    <h3>Hello, <%= @user.name %>! </h3>
    <p>Your profile is created successfully. </p>
    <p>User Name : <%= @user.email %></p>
    <p>User Pass : http://infinite-depths-5848.herokuapp.com/<%= link_to "Get your password", new_doctor_password_path %></p>
  </body>
</html>